spring.datasource.url=${BD_UR}
spring.datasource.username=${BD_USERNAME}
spring.datasource.password=${BD_PASSWORD}

spring.datasource.first.url=${BD_UR}
spring.datasource.first.username=${BD_USERNAME}
spring.datasource.first.password=${BD_PASSWORD}
spring.datasource.first.driverClassName=oracle.jdbc.OracleDriver

spring.datasource.second.url=${BD_UR_2}
spring.datasource.second.username=${BD_USERNAME_2}
spring.datasource.second.password=${BD_PASSWORD_2}

spring.datasource.second.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none

server.port=8080

aut.console.platform = 21

mail.api.url = https://back-mail-${ID_ENVIRONMENT}-ue.a.run.app/api/mail
auth.api.url = https://back-auth-${ID_ENVIRONMENT}-ue.a.run.app/api/auth/token
authorization.api.url = https://back-authorization-${ID_ENVIRONMENT}-ue.a.run.app/api/authorization
connect.external.api.url = https://back-connect-internet-${ID_ENVIRONMENT}-ue.a.run.app/api/access-internet


#spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=on)(FAILOVER=on)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.21.235)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.21.236)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.21.237)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ACTIV)))
#spring.datasource.username=data_an
#spring.datasource.password=Marzo.2024
#
#spring.datasource.first.url=jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=on)(FAILOVER=on)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.21.235)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.21.236)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.21.237)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ACTIV)))
#spring.datasource.first.username=data_an
#spring.datasource.first.password=Marzo.2024
#spring.datasource.first.driverClassName=oracle.jdbc.OracleDriver
#
#spring.datasource.second.url=jdbc:mysql://35.231.179.95:3306/apps_empresariales
#spring.datasource.second.username=apps
#spring.datasource.second.password=d-G\\0L8c2@Vm)D
#
#spring.datasource.second.driverClassName=com.mysql.cj.jdbc.Driver
#
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.hibernate.ddl-auto=none
#
#server.port=8080
#
#aut.console.platform = 21
#
#mail.api.url = https://back-gateway-hfbop5vthq-ue.a.run.app/api/mail
#auth.api.url = https://back-auth-hfbop5vthq-ue.a.run.app/api/auth/token
#authorization.api.url = https://back-authorization-hfbop5vthq-ue.a.run.app/api/authorization
#connect.external.api.url = https://back-connect-internet-hfbop5vthq-ue.a.run.app/api/access-internet
