spring.datasource.url=jdbc:oracle:thin:@activ-scan.activos.com.co:1521/ACTIV
spring.datasource.username=data_an
spring.datasource.password=Marzo.2024

spring.datasource.first.url=jdbc:oracle:thin:@activ-scan.activos.com.co:1521/ACTIV
spring.datasource.first.username=data_an
spring.datasource.first.password=Marzo.2024
spring.datasource.first.driverClassName=oracle.jdbc.OracleDriver

spring.datasource.second.url=jdbc:mysql://35.231.179.95:3306/apps_empresariales
spring.datasource.second.username=root
spring.datasource.second.password=T:[_<&pU9gNg%9Gu

spring.datasource.second.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none

server.port=8080

aut.console.platform = 21

mail.api.url = https://back-mail-WHATSAPP-ue.a.run.app/api/mail
auth.api.url = https://back-auth-WHATSAPP-ue.a.run.app/api/auth/token
authorization.api.url = https://back-authorization-WHATSAPP-ue.a.run.app/api/authorization
connect.external.api.url = https://back-connect-internet-WHATSAPP-ue.a.run.app/api/access-internet
