spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=on)(FAILOVER=on)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.21.235)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.21.236)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.21.237)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ACTIV)))
spring.datasource.username=data_an
spring.datasource.password=Marzo.2024

spring.datasource.first.url=jdbc:oracle:thin:@(DESCRIPTION=(LOAD_BALANCE=on)(FAILOVER=on)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.21.235)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.21.236)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.21.237)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ACTIV)))
spring.datasource.first.username=data_an
spring.datasource.first.password=Marzo.2024
spring.datasource.first.driverClassName=oracle.jdbc.OracleDriver

spring.datasource.second.url=jdbc:mysql://localhost:3306/apps_empresariales
spring.datasource.second.username=root
spring.datasource.second.password=

spring.datasource.second.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none

server.port=8080


mail.api.url = https://back-mail-dbturhsfja-ue.a.run.app/api/mail
connect.external.api.url = https://back-connect-internet-dbturhsfja-ue.a.run.app/api/access-internet